name: ruby-lsp

type: ruby

up:
  - ruby: 3.1.1
  - bundler
  - node:
      yarn: 1.22.17
      version: v16.14.0
      packages: ["./features/vscode_extension"]

commands:
  style: bin/style
  extension: bin/package_extension
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/test
