name: ruby-lsp

type: ruby

up:
  - ruby: 3.1.1
  - bundler:
      gemfile: server/Gemfile
  - node:
      yarn: 1.22.17
      version: v16.14.0
      packages: ["./client"]

commands:
  server: scripts/start_server
  style: scripts/lint
  extension: scripts/package_extension
  test:
    syntax:
      argument: file
      optional: args...
    run: scripts/test
