name: ruby-lsp

type: ruby

up:
  - ruby: 3.1.1
  - bundler:
      gemfile: Gemfile

commands:
  server: exe/ruby-lsp
  style: bundle exec rubocop
  test:
    syntax:
      argument: file
      optional: args...
    run: bundle exec rake
