name: Benchmark

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      # Setup the main branch to run benchmarks there as a baseline for comparison
      - name: Checkout to main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Main benchmark
        id: main-benchmark
        run: |
         bin/benchmark

      # Setup the PR's branch to run benchmarks and compare with main results
      - name: Checkout to branch
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Branch benchmark
        id: benchmark
        run: |
          result=$(bin/benchmark) || true
          echo "REPORT=$(echo "$result" | tr '\n' '#')" >> $GITHUB_OUTPUT

      # Post the results as a comment on the PR
      - name: Comment report
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '```#${{ steps.benchmark.outputs.REPORT }}#```'.split("#").join("\n"),
            });

      # Fail the job based on the benchmark output
      - name: Finalize job
        run: |
          if [[ "${{ steps.benchmark.outputs.REPORT }}" == *"At least one benchmark is slower than the main branch"* ]]; then
            exit 1
          else
            exit 0
          fi
