name: Benchmark

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip bm]')"
    name: Benchmark
    steps:
      # Setup the main branch to run benchmarks there as a baseline for comparison
      - name: Checkout to main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Main benchmark
        id: main-benchmark
        run: |
         bin/benchmark

      # Setup the PR's branch to run benchmarks and compare with main results
      - name: Checkout to branch
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Branch benchmark
        id: benchmark
        run: |
          result=$(bin/benchmark) || true
          echo "REPORT=$(echo "$result" | tr '\n' '#')" >> $GITHUB_OUTPUT

      # Post the results as a comment on the PR
      - name: Comment report
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const GITHUB_ACTIONS_USER_ID = 41898282
            const BODY_COMMENT = '```#${{ steps.benchmark.outputs.REPORT }}#```'.split("#").join("\n")

            const { data: issueComments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            commentToUpdate = issueComments.find(comment => {
              const { body, user: { id } } = comment
              return id === GITHUB_ACTIONS_USER_ID && body.includes("Benchmark results")
            })

            if (commentToUpdate) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: commentToUpdate.id,
                body: BODY_COMMENT,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: BODY_COMMENT,
              });
            }

      # Fail the job based on the benchmark output
      - name: Finalize job
        run: |
          report="${{ steps.benchmark.outputs.REPORT }}"
          if [[ "$report" == *"At least one benchmark is slower than the main branch"* ]] || [[ "$report" == *"Missing benchmarks"* ]]; then
            exit 1
          else
            exit 0
          fi
