name: Benchmark

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Benchmark
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      # Restore the cached benchmark results from the main branch to compare it with the current branch
      - name: Restore main benchmark results
        id: restore-main-results
        uses: actions/cache/restore@v3
        if: github.event_name == 'pull_request'
        with:
          path: |
            /tmp/ruby_lsp_benchmark_results.json
          key: main-benchmark-results

      # Run the benchmark. The script reads the cache and compares the results between the PR's branch and main
      - name: Benchmark
        id: benchmark
        run: |
          result=$(bin/benchmark) || true
          echo "REPORT=$(echo "$result" | tr '\n' '#')" >> $GITHUB_OUTPUT

      - name: Comment report
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '```#${{ steps.benchmark.outputs.REPORT }}#```'.split("#").join("\n"),
            });

      - name: Finalize job
        run: |
          if [[ "${{ steps.benchmark.outputs.REPORT }}" == *"At least one benchmark is 15% slower than the main branch"* ]]; then
            exit 1
          else
            exit 0
          fi

      # Only cache benchmark results from the main branch
      - name: Save main benchmark results
        id: save-main-results
        uses: actions/cache/save@v3
        if: github.ref_name == 'main'
        with:
          path: |
            /tmp/ruby_lsp_benchmark_results.json
          key: main-benchmark-results
